version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: qoden
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xna004
  migrations:
    depends_on:
      - db
    build:
      context: .
      dockerfile: migrations.Dockerfile
    image: migrations
    environment:
      DB_HOST: db
      DB_TYPE: jdbc:postgresql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: xna004
      DB_NAME: qoden
      DB_DRIVER: org.postgresql.Driver
      LOGLEVEL: debug
      CONTEXTS: dev
    entrypoint: ["./wait-for-it.sh", "-s", "-t", "15", "db:5432","--", "./run-migrations.sh"]
  api:
    depends_on:
      - db
      - migrations
    build:
      context: .
      dockerfile: api.Dockerfile
    image: api
    ports:
      - 5000:80


